# application.properties - ms-sucursales
# Configuración del Maestro de Sedes y Tiendas Físicas para BookPoint Chile
# Arquitecto de Software: Antigravity

# Puerto del Servidor local
server.port=8090

# Nombre del Microservicio
spring.application.name=ms-sucursales

# Configuración de Base de Datos MySQL (Esquema: bookpoint_sucursales)
spring.datasource.url=jdbc:mysql://localhost:3306/bookpoint_sucursales?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

# Configuración JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Registro y Descubrimiento Eureka (Desactivado localmente)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.enabled=false

# Habilitar logging del nivel INFO para trazabilidad de tiendas físicas
logging.level.cl.bookpointchile.sucursales=INFO
